trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job_Python38
  displayName: 'Python 3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python 3.8'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: Job_Python39
  displayName: 'Python 3.9'
  dependsOn: Job_Python38
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: Job_Python310
  displayName: 'Python 3.10'
  dependsOn: Job_Python39
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Use Python 3.10'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: Job_Python311
  displayName: 'Python 3.11'
  dependsOn: Job_Python310
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: 'Use Python 3.11'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'